# Generated by Django 3.2 on 2021-05-01 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='room_name',
        ),
    ]
