# Generated by Django 3.2 on 2021-05-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_notification_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='room_name',
            field=models.CharField(blank=True, default='Anonymous room', max_length=30),
        ),
    ]
