# Generated by Django 3.2 on 2021-04-26 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_alter_room_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friends', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('this_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='this_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
