# Generated by Django 3.2 on 2021-04-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_friendship_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='requesting_username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
